theme = "sugoi"
baseURL = "/"
languageCode = "en-us"
title = "Songwriter"
summaryLength = 20
paginate = 5
hero = { }
themesDir = "themes"
publishDir = "public"

[params]
favicon = "images/favicon.png"
herotitle = "Songwriter"
herolink = "https://github.com/aanupam23/hugo-sugoi"
herolinktext = "Check Now"
contact = "Send me a message and I will get back as soon as possible."

[[menu.nav]]
name = "about"
pre = "<i class='fas fa-home'></i>"
url = "about"
weight = -1

[[menu.nav]]
name = "blog"
pre = "<i class='fas fa-list'></i>"
url = "post"
weight = -2

[[menu.nav]]
name = "contact"
pre = "<i class='fas fa-envelope'></i>"
url = "contact"
weight = -3
